# Generated by Django 4.2.11 on 2024-04-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabySitterattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('attendance_status', models.CharField(choices=[('On_duty', 'On_duty'), ('Off_duty', 'Off_duty')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('picked_up_by', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, verbose_name='Comment(optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('Unit_Price', models.IntegerField(default=0)),
                ('Quantity_Price', models.IntegerField(default=0)),
                ('Total_Price', models.IntegerField(default=0)),
                ('Total_Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paymenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('Date_Of_Birth', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('Baby_Number', models.CharField(default=0, max_length=200)),
                ('Parents_Name', models.CharField(max_length=200)),
                ('Brought_by', models.CharField(max_length=200)),
                ('Time_In', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Period_of_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorystay')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='Ugx', max_length=5)),
                ('paid_by', models.CharField(max_length=200)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.paymenttype')),
                ('period_of_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categorystay')),
            ],
        ),
        migrations.CreateModel(
            name='BabySitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('Date_Of_Birth', models.DateTimeField()),
                ('NIN', models.CharField(max_length=14)),
                ('Religion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Religion(optional)')),
                ('Level_Of_Education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Others', 'Others')], max_length=200)),
                ('Contact', models.CharField(max_length=15)),
                ('Sitter_Number', models.CharField(max_length=200)),
                ('Next_Of_Kin', models.CharField(max_length=200)),
                ('Recommenders_Name', models.CharField(max_length=200)),
                ('Recommenders_Contact', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fixedlocation')),
            ],
        ),
    ]
