# Generated by Django 4.2.11 on 2024-05-14 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('payment_date', models.DateField()),
                ('full_day', models.BooleanField(blank=True, default=False)),
                ('half_day', models.BooleanField(blank=True, default=False)),
                ('monthly', models.BooleanField(blank=True, default=False)),
                ('total_amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BabySitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('location', models.CharField(default='kabalagala', max_length=10)),
                ('Date_Of_Birth', models.DateField(default=django.utils.timezone.now)),
                ('NIN', models.CharField(max_length=14, validators=[myapp.models.validate_NIN_length])),
                ('Religion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Religion(optional)')),
                ('Level_Of_Education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Others', 'Others')], max_length=200)),
                ('Contact', models.CharField(max_length=10, validators=[myapp.models.validate_contact_length])),
                ('Sitter_Number', models.CharField(max_length=200, null=True, unique=True)),
                ('Next_Of_Kin', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('Recommenders_Name', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('Recommenders_Contact', models.CharField(max_length=10, validators=[myapp.models.validate_contact_length])),
            ],
        ),
        migrations.CreateModel(
            name='BabySitterattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitter_Number', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_status', models.CharField(default='Onduty', max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.babysitter')),
            ],
        ),
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doll', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=200, null=True, validators=[myapp.models.validate_letters])),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_doll')),
            ],
        ),
        migrations.CreateModel(
            name='Issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued_out', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('Baby_Number', models.CharField(max_length=200, null=True, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('Parents_Name', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('Brought_by', models.CharField(max_length=200, validators=[myapp.models.validate_letters])),
                ('Fee_in_UGX', models.IntegerField()),
                ('Time_In', models.DateTimeField()),
                ('Assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.babysitterattendance')),
                ('Period_of_stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorystay')),
            ],
        ),
        migrations.CreateModel(
            name='Sitterpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('baby_count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=3000)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.babysitterattendance')),
            ],
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by', models.CharField(blank=True, max_length=200, null=True, validators=[myapp.models.validate_letters])),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registerbaby')),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateField(default=django.utils.timezone.now)),
                ('quantity_bought', models.IntegerField(default=0)),
                ('amount_in_Ugx', models.IntegerField()),
                ('quantity_issued_out', models.IntegerField(default=0)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.items')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('picked_up_by', models.CharField(max_length=100, validators=[myapp.models.validate_letters])),
                ('comment', models.TextField(blank=True, verbose_name='Comment(optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registerbaby')),
            ],
        ),
    ]
