# Generated by Django 4.2.11 on 2024-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitterattendance',
            name='sitter_Number',
        ),
    ]
