# Generated by Django 4.2.11 on 2024-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytracker',
            name='QuantityPrice',
        ),
        migrations.RemoveField(
            model_name='inventorytracker',
            name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='inventorytracker',
            name='TotalPrice',
        ),
        migrations.RemoveField(
            model_name='inventorytracker',
            name='UnitPrice',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='Fee',
        ),
        migrations.AddField(
            model_name='inventorytracker',
            name='Quantity_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytracker',
            name='Total_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytracker',
            name='Total_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytracker',
            name='Unit_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorytracker',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
