# Generated by Django 4.2.11 on 2024-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypayment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
