# Generated by Django 4.2.11 on 2024-05-02 06:44

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='NIN',
            field=models.CharField(max_length=14, validators=[myapp.models.validate_NIN_length]),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='Next_Of_Kin',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='Recommenders_Contact',
            field=models.CharField(max_length=10, validators=[myapp.models.validate_contact_length]),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='Recommenders_Name',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='departure',
            name='baby_name',
            field=models.CharField(max_length=100, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='doll',
            name='name_of_the_doll',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='registerbaby',
            name='Parents_Name',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='registerbaby',
            name='name',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='baby_name',
            field=models.CharField(max_length=200, validators=[myapp.models.validate_letters]),
        ),
    ]
