# Generated by Django 4.2.11 on 2024-04-29 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
