# Generated by Django 4.2.11 on 2024-04-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivalbaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=200)),
                ('Brought_by', models.CharField(max_length=200)),
                ('Time_In', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='Brought_by',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='Time_In',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='created_at',
        ),
    ]
