# Generated by Django 4.2.11 on 2024-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='full_day',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='half_day',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='monthly',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
