# Generated by Django 4.2.11 on 2024-04-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('DateOfBirth', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('BabyNumber', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('FeeInUgx', models.IntegerField(blank=True, default=0, null=True)),
                ('ParentsOrGuardiansName', models.CharField(blank=True, max_length=200, null=True)),
                ('ParentsOrGuardiansConatct', models.CharField(blank=True, max_length=200, null=True)),
                ('PeriodOfStay', models.CharField(blank=True, max_length=200, null=True)),
                ('DateOfRegistartion', models.DateTimeField(blank=True, default=0, null=True)),
                ('MoreInfromationAboutTheBaby', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabySitters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('NIN', models.IntegerField(blank=True, null=True)),
                ('Religion', models.CharField(blank=True, max_length=30, null=True)),
                ('LevelOfEducation', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('SitterNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('NextOfKin', models.CharField(blank=True, max_length=200, null=True)),
                ('RecommendersName', models.CharField(blank=True, max_length=200, null=True)),
                ('RecommendersContact', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('UnitPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('QuantityPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('TotalPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('TotalAmount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=5, null=True)),
                ('c_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categorystay')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterBaby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('DateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('BabyNumber', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('FeeInUgx', models.IntegerField(blank=True, default=0, null=True)),
                ('PaymentTime', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('NameOfThePersonThatHasBroughtTheBaby', models.CharField(blank=True, max_length=200, null=True)),
                ('NameOfThePersonThatHasTakenTheBaby', models.CharField(blank=True, max_length=200, null=True)),
                ('PeriodOfStay', models.CharField(blank=True, max_length=200, null=True)),
                ('TimeIn', models.DateTimeField(blank=True, null=True)),
                ('TimeOut', models.DateTimeField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, max_length=500, null=True)),
                ('c_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
                ('c_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categorystay')),
            ],
        ),
        migrations.DeleteModel(
            name='Arrival',
        ),
        migrations.DeleteModel(
            name='Babyreg',
        ),
        migrations.DeleteModel(
            name='Forgotpassword',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='Sitterreg',
        ),
    ]
