# Generated by Django 4.2.11 on 2024-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='location',
            field=models.CharField(default='kabalagala', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='Ugx', max_length=5),
        ),
    ]
