# Generated by Django 4.2.11 on 2024-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('full_day', models.BooleanField(default=False)),
                ('half_day', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
