# Generated by Django 4.2.11 on 2024-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_babypayment_full_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10, null=True),
        ),
    ]
