# Generated by Django 4.2.11 on 2024-05-04 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_babypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitterpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('baby_count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=3000)),
                ('sitter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.babysitterattendance')),
            ],
        ),
    ]
