# Generated by Django 4.2.11 on 2024-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_inventorytracker_quantityprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
    ]
