# Generated by Django 4.2.11 on 2024-04-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addbaby_babysitters_categorystay_inventorytracker_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BabySitters',
            new_name='BabySitter',
        ),
    ]
