# Generated by Django 4.2.11 on 2024-04-28 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_arrivalbaby_remove_registerbaby_brought_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_doll', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('c_doll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_doll')),
            ],
        ),
        migrations.CreateModel(
            name='Salesrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('amount_received', models.IntegerField(default=0)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_price', models.IntegerField(default=0)),
                ('doll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doll')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registerbaby')),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryTracker',
        ),
    ]
