# Generated by Django 4.2.11 on 2024-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_babysitter_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='Sitter_Number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registerbaby',
            name='Baby_Number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
