# Generated by Django 4.2.11 on 2024-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_babysitter_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabySitterattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('attendance_status', models.CharField(choices=[('On_duty', 'On_duty'), ('Off_duty', 'Off_duty')], max_length=10)),
            ],
        ),
    ]
