# Generated by Django 4.2.11 on 2024-04-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_babysitters_babysitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerbaby',
            old_name='PaymentTime',
            new_name='Parents_Name',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='FeeInUgx',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='PeriodOfStay',
        ),
    ]
