# Generated by Django 4.2.11 on 2024-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_uniquesitternumberfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='Sitter_Number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
