# Generated by Django 4.2.11 on 2024-05-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sitterpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitterpayment',
            old_name='numbers_of_babies_attended_to',
            new_name='baby_count',
        ),
    ]
