# Generated by Django 4.2.11 on 2024-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_babysitter_sitter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitterattendance',
            name='sitter_Number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
