# Generated by Django 4.2.11 on 2024-04-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_babysitter_sitter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbaby',
            name='Baby_Number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
