# Generated by Django 4.2.11 on 2024-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_paymenttime_registerbaby_parents_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerbaby',
            old_name='NameOfThePersonThatHasBroughtTheBaby',
            new_name='Name_Of_The_Person_That_Has_Brought_The_Baby',
        ),
        migrations.RenameField(
            model_name='registerbaby',
            old_name='NameOfThePersonThatHasTakenTheBaby',
            new_name='Name_Of_The_Person_That_Has_Taken_The_Baby',
        ),
        migrations.AlterField(
            model_name='registerbaby',
            name='Parents_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
