# Generated by Django 4.2.11 on 2024-04-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_nameofthepersonthathasbroughtthebaby_registerbaby_name_of_the_person_that_has_brought_the_bab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddBaby',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='DateOfBirth',
            new_name='Date_Of_Birth',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='LevelOfEducation',
            new_name='Level_Of_Education',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='NextOfKin',
            new_name='Next_Of_Kin',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='RecommendersContact',
            new_name='Recommenders_Contact',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='RecommendersName',
            new_name='Recommenders_Name',
        ),
        migrations.RenameField(
            model_name='babysitter',
            old_name='SitterNumber',
            new_name='Sitter_Number',
        ),
        migrations.RenameField(
            model_name='registerbaby',
            old_name='BabyNumber',
            new_name='Baby_Number',
        ),
        migrations.RenameField(
            model_name='registerbaby',
            old_name='DateOfBirth',
            new_name='Date_Of_Birth',
        ),
    ]
