# Generated by Django 4.2.11 on 2024-05-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_babypayment_total_amount_due_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymenttype',
        ),
    ]
