# Generated by Django 4.2.11 on 2024-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_addbaby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbaby',
            name='Comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
