# Generated by Django 4.2.11 on 2024-04-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_registerbaby_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerbaby',
            old_name='Name_Of_The_Person_That_Has_Brought_The_Baby',
            new_name='Brought_by',
        ),
        migrations.RenameField(
            model_name='registerbaby',
            old_name='Name_Of_The_Person_That_Has_Taken_The_Baby',
            new_name='Picked_up_by',
        ),
        migrations.RemoveField(
            model_name='registerbaby',
            name='Comment',
        ),
    ]
