# Generated by Django 4.2.11 on 2024-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_name_of_the_person_that_has_brought_the_baby_registerbaby_brought_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Picked_up_by', models.CharField(blank=True, max_length=200, null=True)),
                ('Time_Out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
