# Generated by Django 4.2.11 on 2024-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_babypayment_full_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='full_day',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
