# Generated by Django 4.2.11 on 2024-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='comment',
            field=models.TextField(blank='False', max_length=250, null='False'),
            preserve_default='False',
        ),
    ]
