# Generated by Django 4.2.11 on 2024-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_babypayment_full_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kyc',
        ),
    ]
